# Generated by Django 4.2.3 on 2023-07-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_delete_points'),
    ]

    operations = [
    ]
